### ISSUE TITLE
PrestaShop version compatibility?

### ISSUE THREAD

**Issue by Daaaaad** [limegrow/ingenico-ogone-prestashop-payments#13]
Hello I tried to install your module on PS v1.6.1.24 but I get this error message:

[PrestaShop] Fatal error in module file :/var/www/html/modules/ingenico_epayments/ingenico_epayments.php:
Uncaught Error: Call to undefined method Context::getTranslator() in /var/www/html/modules/ingenico_epayments/ingenico_epayments.php:96 Stack trace: #0 [internal function]: Ingenico_Epayments->__construct() #1 /var/www/html/Core/Foundation/IoC/Core_Foundation_IoC_Container.php(124): ReflectionClass->newInstance() #2 /var/www/html/Core/Foundation/IoC/Core_Foundation_IoC_Container.php(157): Core_Foundation_IoC_Container->makeInstanceFromClassName('ingenico_epayme...', Array) #3 /var/www/html/Core/Foundation/IoC/Core_Foundation_IoC_Container.php(170): Core_Foundation_IoC_Container->doMake('ingenico_epayme...', Array) #4 /var/www/html/Adapter/Adapter_ServiceLocator.php(52): Core_Foundation_IoC_Container->make('ingenico_epayme...') #5 /var/www/html/override/classes/module/Module.php(1145): Adapter_ServiceLocator::get('ingenico_epayme...') #6 /var/www/html/override/classes/module/Module.php(1110): ModuleCore::coreLoadModule('ingenico_epayme...') #7 /var/www/html/controllers/admin/AdminModulesController.php(421): Mo

**Comment by olegisk** [comment]
@Daaaaad Hello, sorry, but this module doesn't support PS v1.6. It supports PS v.1.7+
